In [1]:
import pandas as pd

df = pd.read_csv("online_retail_practice_sample.csv")

In [2]:
display(df)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [3]:
print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    570338     71053                  WHITE METAL LANTERN         7
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
2    545052    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         0
3    567005     71053                  WHITE METAL LANTERN        12
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15

           InvoiceDate  UnitPrice  CustomerID      Country
0  2011-09-15 15:26:00       4.07     16640.0       Sweden
1  2011-06-05 08:10:00       4.25     17154.0       Sweden
2  2011-07-24 03:45:00       3.39     16783.0  Netherlands
3  2011-09-04 16:55:00       3.39     14222.0        Spain
4  2011-02-23 13:40:00       3.39     16830.0       Sweden

In [4]:
print(df.tail(10))

     InvoiceNo StockCode                          Description  Quantity  \
1602    576798     22633               HAND WARMER UNION JACK         8
1603    549401     21730    GLASS STAR FROSTED T-LIGHT HOLDER         5
1604    565607    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         1
1605    569476     22423             REGENCY CAKESTAND 3 TIER         4
1606   C554322     21212      PACK OF 72 RETROSPOT CAKE CASES        -6
1607    546730     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
1608    556479     22423             REGENCY CAKESTAND 3 TIER        13
1609   C541876     21730    GLASS STAR FROSTED T-LIGHT HOLDER        -7
1610    553299    85123A   WHITE HANGING HEART T-LIGHT HOLDER         8
1611    537515    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6

              InvoiceDate  UnitPrice  CustomerID      Country
1602  2011-03-20 15:46:00       2.10     16068.0    Australia
1603  2011-05-25 22:09:00       3.40     13436.0     Portugal
1604  2011-07-24 17:52:00       2.71     13346.0  Netherlands
1605  2011-04-19 21:53:00      12.75     17314.0       Sweden
1606  2011-08-16 02:22:00       0.55     18187.0       Sweden
1607  2011-09-20 00:21:00       4.25     16326.0        Spain
1608  2011-11-13 09:05:00      12.75     13615.0         EIRE
1609  2011-04-07 12:48:00       5.10     16943.0        Spain
1610  2011-09-24 16:24:00       2.55     17478.0     Portugal
1611  2011-08-24 00:48:00       2.55     17296.0      Germany

In [5]:
print(df.sample(15))

     InvoiceNo StockCode                         Description  Quantity  \
1088    555967     22633              HAND WARMER UNION JACK         9
267     572385    79323P                                 NaN         1
652     566960     21977  PACK OF 60 PINK PAISLEY CAKE CASES         6
1257    580538     71053                 WHITE METAL LANTERN         4
1417    546855     21730   GLASS STAR FROSTED T-LIGHT HOLDER        14
992     566179     71053                 WHITE METAL LANTERN         4
979     580236    85123A  WHITE HANGING HEART T-LIGHT HOLDER        14
156     558431     21730   GLASS STAR FROSTED T-LIGHT HOLDER         2
991     547594    85123A  WHITE HANGING HEART T-LIGHT HOLDER        14
1599    570077     21730   GLASS STAR FROSTED T-LIGHT HOLDER        10
112     537401     22633              HAND WARMER UNION JACK         1
900     565023     22752        SET 7 BABUSHKA NESTING BOXES         1
1475    570062     22752        SET 7 BABUSHKA NESTING BOXES         3
498     568062    79323P                  PINK CHERRY LIGHTS         3
773     540028     22752        SET 7 BABUSHKA NESTING BOXES        11

              InvoiceDate  UnitPrice  CustomerID      Country
1088  2011-10-17 10:16:00       2.52     13745.0      Belgium
267   2011-06-10 16:31:00       8.10     15755.0  Netherlands
652   2011-06-15 16:35:00       0.66     14841.0      Germany
1257  2011-04-14 08:42:00       4.07     17916.0       France
1417  2011-01-13 09:11:00       5.10     16074.0    Australia
992   2011-02-17 04:44:00       3.39     17938.0        Spain
979   2011-08-28 18:55:00       2.55     15845.0    Australia
156   2011-11-09 10:58:00       4.25     13645.0       Sweden
991   2011-05-28 17:30:00       3.06         NaN  Netherlands
1599  2011-09-23 17:30:00       4.25     12345.0      Belgium
112   2011-03-06 07:37:00       2.10     15512.0    Australia
900   2011-01-20 01:50:00       9.18     15829.0    Australia
1475  2011-04-14 18:56:00       7.65     13511.0        Spain
498   2010-12-22 12:20:00       5.40     15504.0       Sweden
773   2011-11-26 22:49:00       6.12     18011.0       Sweden

In [6]:
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Total rows: 1612
Total columns: 8

In [7]:
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [8]:
print(df.dtypes)

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [9]:
rows, columns = df.shape

print("Original number of rows:", rows)
print("Original number of columns:", columns)

Original number of rows: 1612
Original number of columns: 8

In [10]:
print(df["Description"].head(20))

0                     WHITE METAL LANTERN
1       GLASS STAR FROSTED T-LIGHT HOLDER
2     KNITTED UNION FLAG HOT WATER BOTTLE
3                     WHITE METAL LANTERN
4     KNITTED UNION FLAG HOT WATER BOTTLE
5     KNITTED UNION FLAG HOT WATER BOTTLE
6                                 POSTAGE
7                                 POSTAGE
8      PACK OF 60 PINK PAISLEY CAKE CASES
9                     WHITE METAL LANTERN
10                 HAND WARMER UNION JACK
11        PACK OF 72 RETROSPOT CAKE CASES
12                                POSTAGE
13           SET 7 BABUSHKA NESTING BOXES
14      GLASS STAR FROSTED T-LIGHT HOLDER
15     PACK OF 60 PINK PAISLEY CAKE CASES
16                                POSTAGE
17               REGENCY CAKESTAND 3 TIER
18                     PINK CHERRY LIGHTS
19               REGENCY CAKESTAND 3 TIER
Name: Description, dtype: object

### Project Phase 2

In [11]:
selected_df = df[[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "UnitPrice",
    "CustomerID",
    "Country"
]]

display(selected_df.head())

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden

In [12]:
first_10 = df.head(10)

display(first_10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,2011-02-28 16:38:00,4.07,12343.0,Spain
6,570510,POST,POSTAGE,4,2011-07-01 00:08:00,14.40,12767.0,United Kingdom
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.60,13566.0,France
8,572698,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2,2011-03-20 10:39:00,0.55,14765.0,Germany
9,547022,71053,WHITE METAL LANTERN,7,2011-09-14 17:41:00,4.07,15256.0,EIRE

In [13]:
print(df.describe())

          Quantity    UnitPrice    CustomerID
count  1612.000000  1612.000000   1541.000000
mean      7.158189     5.523189  15201.415315
std       5.890089     5.191564   1693.230069
min     -15.000000     0.000000  12305.000000
25%       4.000000     2.200000  13708.000000
50%       8.000000     3.390000  15220.000000
75%      12.000000     7.650000  16640.000000
max      15.000000    21.600000  18196.000000

In [14]:
print(df[["Country", "Description"]].describe())

       Country Description
count     1599        1589
unique      10          22
top     France     POSTAGE
freq       178         143

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1612 non-null   object
 1   StockCode    1612 non-null   object
 2   Description  1589 non-null   object
 3   Quantity     1612 non-null   int64
 4   InvoiceDate  1612 non-null   object
 5   UnitPrice    1612 non-null   float64
 6   CustomerID   1541 non-null   float64
 7   Country      1599 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 100.9+ KB

In [16]:
print(df.isnull().sum())

InvoiceNo       0
StockCode       0
Description    23
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID     71
Country        13
dtype: int64

In [17]:
print("Unique invoices:", df["InvoiceNo"].nunique())
print("Unique products:", df["StockCode"].nunique())
print("Unique countries:", df["Country"].nunique())
print("Identified customers:", df["CustomerID"].nunique())

Unique invoices: 1574
Unique products: 12
Unique countries: 10
Identified customers: 1346

In [18]:
print(df["Country"].unique())

print("Number of countries:", df["Country"].nunique())

['Sweden' 'Netherlands' 'Spain' 'United Kingdom' 'France' 'Germany' 'EIRE'
 'Portugal' 'Belgium' 'Australia' nan]
Number of countries: 10

In [19]:
country_counts = df["Country"].value_counts()

print(country_counts.head(10))

Country
France            178
Spain             165
Australia         165
Belgium           164
Sweden            162
United Kingdom    160
Netherlands       158
EIRE              155
Portugal          147
Germany           145
Name: count, dtype: int64

In [20]:
summary = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Unique Products",
        "Unique Invoices"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        df["StockCode"].nunique(),
        df["InvoiceNo"].nunique()
    ]
})

display(summary)

            Metric  Value
0       Total Rows   1612
1    Total Columns      8
2  Unique Products     12
3  Unique Invoices   1574

In [21]:
profile = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Unique Products",
        "Unique Invoices",
        "Unique Countries",
        "Identified Customers",
        "Missing Values"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        df["StockCode"].nunique(),
        df["InvoiceNo"].nunique(),
        df["Country"].nunique(),
        df["CustomerID"].nunique(),
        df.isnull().sum().sum()
    ]
})

profile.to_csv("dataset_profile.csv", index=False)

print("Dataset profile exported successfully.")

Dataset profile exported successfully.

In [22]:
df[["InvoiceNo", "InvoiceDate"]]

     InvoiceNo          InvoiceDate
0       570338  2011-09-15 15:26:00
1       574674  2011-06-05 08:10:00
2       545052  2011-07-24 03:45:00
3       567005  2011-09-04 16:55:00
4       573512  2011-02-23 13:40:00
...        ...                  ...
1607    546730  2011-09-20 00:21:00
1608    556479  2011-11-13 09:05:00
1609   C541876  2011-04-07 12:48:00
1610    553299  2011-09-24 16:24:00
1611    537515  2011-08-24 00:48:00

[1612 rows x 2 columns]

In [23]:

df.iloc[5]

InvoiceNo                                   561166
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                         3
InvoiceDate                    2011-02-28 16:38:00
UnitPrice                                     4.07
CustomerID                                 12343.0
Country                                      Spain
Name: 5, dtype: object

In [24]:
df.iloc[0:5, 0:3]

  InvoiceNo StockCode                          Description
0    570338     71053                  WHITE METAL LANTERN
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER
2    545052    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
3    567005     71053                  WHITE METAL LANTERN
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE

In [25]:
df.loc[0:5, ["InvoiceNo", "Quantity", "UnitPrice"]]

  InvoiceNo  Quantity  UnitPrice
0    570338         7       4.07
1    574674        14       4.25
2    545052         0       3.39
3    567005        12       3.39
4    573512        15       3.39
5    561166         3       4.07

In [26]:

high_quantity = df[df["Quantity"] > 10]

print(high_quantity.head(10))
print("Total records:", len(high_quantity))

   InvoiceNo StockCode                          Description  Quantity  \
1     574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
3     567005     71053                  WHITE METAL LANTERN        12
4     573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
10    567596     22633               HAND WARMER UNION JACK        15
18    580659    79323P                   PINK CHERRY LIGHTS        15
21    579630    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
22    569349    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        12
24    578010     71053                  WHITE METAL LANTERN        11
26    547427    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        14
31    550785     22423             REGENCY CAKESTAND 3 TIER        15

            InvoiceDate  UnitPrice  CustomerID      Country
1   2011-06-05 08:10:00       4.25     17154.0       Sweden
3   2011-09-04 16:55:00       3.39     14222.0        Spain
4   2011-02-23 13:40:00       3.39     16830.0       Sweden
10  2011-07-24 14:21:00       1.68     15220.0       France
18  2011-06-11 21:15:00       8.10     18019.0       Sweden
21  2011-12-08 18:19:00       3.39     13148.0      Germany
22  2011-06-07 22:41:00       3.39     12797.0  Netherlands
24  2011-07-25 20:06:00       2.71     13370.0      Belgium
26  2011-05-03 02:22:00       3.39     15432.0       Sweden
31  2011-09-25 21:14:00      12.75     16898.0  Netherlands
Total records: 527

In [27]:

expensive_items = df[df["UnitPrice"] > 50]

print(expensive_items.head(10))
print("Total records:", len(expensive_items))

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []
Total records: 0

In [28]:

uk_sales = df[df["Country"] == "United Kingdom"]

print(uk_sales.head())
print("Total UK records:", len(uk_sales))

   InvoiceNo StockCode                          Description  Quantity  \
6     570510      POST                              POSTAGE         4
42    575608    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         8
69    566686     22423             REGENCY CAKESTAND 3 TIER        13
71    561128     22633               HAND WARMER UNION JACK         6
79    557907     22423             REGENCY CAKESTAND 3 TIER         5

            InvoiceDate  UnitPrice  CustomerID         Country
6   2011-07-01 00:08:00      14.40     12767.0  United Kingdom
42  2011-05-14 00:18:00       4.07     12560.0  United Kingdom
69  2011-06-14 08:46:00      12.75     15782.0  United Kingdom
71  2011-09-01 14:03:00       2.10     15231.0  United Kingdom
79  2011-06-16 06:13:00      15.30     15131.0  United Kingdom
Total UK records: 160

In [29]:

top_5_countries = df["Country"].value_counts().head(5)

print(top_5_countries)

Country
France       178
Spain        165
Australia    165
Belgium      164
Sweden       162
Name: count, dtype: int64

In [30]:

top_country_transactions = df[
    df["Country"].isin(top_5_countries.index)
]

print(top_country_transactions.head())
print("Total records:", len(top_country_transactions))

  InvoiceNo StockCode                          Description  Quantity  \
0    570338     71053                  WHITE METAL LANTERN         7
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
3    567005     71053                  WHITE METAL LANTERN        12
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
5    561166    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         3

           InvoiceDate  UnitPrice  CustomerID Country
0  2011-09-15 15:26:00       4.07     16640.0  Sweden
1  2011-06-05 08:10:00       4.25     17154.0  Sweden
3  2011-09-04 16:55:00       3.39     14222.0   Spain
4  2011-02-23 13:40:00       3.39     16830.0  Sweden
5  2011-02-28 16:38:00       4.07     12343.0   Spain
Total records: 834

In [31]:

quantity_range = df[
    df["Quantity"].between(5, 20)
]

print(quantity_range.head())
print("Total records:", len(quantity_range))

  InvoiceNo StockCode                          Description  Quantity  \
0    570338     71053                  WHITE METAL LANTERN         7
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
3    567005     71053                  WHITE METAL LANTERN        12
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
9    547022     71053                  WHITE METAL LANTERN         7

           InvoiceDate  UnitPrice  CustomerID Country
0  2011-09-15 15:26:00       4.07     16640.0  Sweden
1  2011-06-05 08:10:00       4.25     17154.0  Sweden
3  2011-09-04 16:55:00       3.39     14222.0   Spain
4  2011-02-23 13:40:00       3.39     16830.0  Sweden
9  2011-09-14 17:41:00       4.07     15256.0    EIRE
Total records: 1151

In [32]:

filtered_sales = df.query(
    "Quantity > 10 and UnitPrice > 5"
)

print(filtered_sales.head(10))
print("Total records:", len(filtered_sales))

    InvoiceNo StockCode                   Description  Quantity  \
18     580659    79323P            PINK CHERRY LIGHTS        15
31     550785     22423      REGENCY CAKESTAND 3 TIER        15
38     566325     22423      REGENCY CAKESTAND 3 TIER        11
69     566686     22423      REGENCY CAKESTAND 3 TIER        13
89     577425     22752  SET 7 BABUSHKA NESTING BOXES        14
97     553102      POST                       POSTAGE        13
98     545596      POST                       POSTAGE        13
113    572481    79323P            PINK CHERRY LIGHTS        15
119    544302    79323P            PINK CHERRY LIGHTS        15
129    557071    79323P            PINK CHERRY LIGHTS        14

             InvoiceDate  UnitPrice  CustomerID         Country
18   2011-06-11 21:15:00       8.10     18019.0          Sweden
31   2011-09-25 21:14:00      12.75     16898.0     Netherlands
38   2011-01-14 18:07:00      10.20     13528.0          Sweden
69   2011-06-14 08:46:00      12.75     15782.0  United Kingdom
89   2011-11-16 02:46:00       6.12     16327.0          Sweden
97   2011-05-08 02:48:00      18.00     15499.0     Netherlands
98   2011-09-01 17:17:00      18.00     12554.0          France
113  2011-04-15 10:10:00       6.75     14201.0          France
119  2010-12-01 23:01:00       5.40     12861.0           Spain
129  2011-09-17 04:50:00       8.10     15108.0         Germany
Total records: 203

In [33]:

top_20_prices = df.sort_values(
    by="UnitPrice",
    ascending=False
).head(20)

print(top_20_prices)

     InvoiceNo StockCode Description  Quantity          InvoiceDate  \
1248    565100      POST     POSTAGE        14  2011-11-25 20:27:00
1253    573477      POST     POSTAGE         8  2011-04-22 14:47:00
49      557529      POST     POSTAGE         7  2011-08-19 06:38:00
465     569506      POST     POSTAGE         6  2011-11-08 11:22:00
932    C561717      POST     POSTAGE       -11  2011-11-22 12:10:00
1528    565108      POST     POSTAGE        10  2011-03-29 08:51:00
1560    567925      POST     POSTAGE         4  2011-01-20 13:21:00
101     573603      POST     POSTAGE         8  2011-03-16 11:27:00
764     572968      POST     POSTAGE         6  2011-07-22 19:28:00
502    C543573      POST     POSTAGE       -15  2011-05-26 09:37:00
833     574836      POST     POSTAGE         2  2011-05-21 21:25:00
501     552616      POST     POSTAGE         6  2011-05-15 13:37:00
752     549960      POST     POSTAGE        15  2011-10-20 05:17:00
353     570905      POST     POSTAGE        12  2011-05-18 16:49:00
359     547600      POST     POSTAGE         8  2011-10-08 10:31:00
456     578392      POST     POSTAGE         1  2010-12-16 14:40:00
1601    540834      POST     POSTAGE        14  2011-01-26 11:06:00
7       574557      POST     POSTAGE         1  2011-09-23 07:36:00
617     540834      POST     POSTAGE        14  2011-01-26 11:06:00
893     565522      POST     POSTAGE         1  2011-08-02 16:33:00

      UnitPrice  CustomerID         Country
1248       21.6     13873.0       Australia
1253       21.6     18172.0            EIRE
49         21.6     17690.0       Australia
465        21.6     16513.0       Australia
932        21.6     15675.0     Netherlands
1528       21.6     16176.0          France
1560       21.6     17041.0          France
101        21.6     14863.0       Australia
764        21.6     16251.0         Germany
502        21.6     17799.0           Spain
833        21.6     14562.0            EIRE
501        21.6     12473.0          France
752        21.6     14865.0       Australia
353        21.6         NaN  United Kingdom
359        21.6     14477.0        Portugal
456        21.6     15550.0         Germany
1601       21.6     13594.0  United Kingdom
7          21.6     13566.0          France
617        21.6     13594.0  United Kingdom
893        21.6     13623.0  United Kingdom

### Phase 4

In [34]:

df_raw = df.copy()

print("Original dataset shape:", df_raw.shape)
print("Working dataset shape:", df.shape)

Original dataset shape: (1612, 8)
Working dataset shape: (1612, 8)

In [35]:

df = df_raw.copy()

print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    570338     71053                  WHITE METAL LANTERN         7
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
2    545052    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         0
3    567005     71053                  WHITE METAL LANTERN        12
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15

           InvoiceDate  UnitPrice  CustomerID      Country
0  2011-09-15 15:26:00       4.07     16640.0       Sweden
1  2011-06-05 08:10:00       4.25     17154.0       Sweden
2  2011-07-24 03:45:00       3.39     16783.0  Netherlands
3  2011-09-04 16:55:00       3.39     14222.0        Spain
4  2011-02-23 13:40:00       3.39     16830.0       Sweden

In [36]:

df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce"
)

print(df["InvoiceDate"].dtype)
print(df["InvoiceDate"].head())

datetime64[ns]
0   2011-09-15 15:26:00
1   2011-06-05 08:10:00
2   2011-07-24 03:45:00
3   2011-09-04 16:55:00
4   2011-02-23 13:40:00
Name: InvoiceDate, dtype: datetime64[ns]

In [37]:

print("Missing invoice dates:", df["InvoiceDate"].isna().sum())

Missing invoice dates: 0

In [38]:

print(df.isnull().sum())

InvoiceNo       0
StockCode       0
Description    23
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID     71
Country        13
dtype: int64

In [39]:

missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().mean() * 100
    ).round(2)
})

print(missing_summary)

             Missing_Count  Missing_Percentage
InvoiceNo                0                0.00
StockCode                0                0.00
Description             23                1.43
Quantity                 0                0.00
InvoiceDate              0                0.00
UnitPrice                0                0.00
CustomerID              71                4.40
Country                 13                0.81

In [40]:

duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 12

In [41]:

df = df.drop_duplicates().copy()

print("Shape after duplicate removal:", df.shape)

Shape after duplicate removal: (1600, 8)

In [42]:

df["Revenue"] = df["Quantity"] * df["UnitPrice"]

print(
    df[["Quantity", "UnitPrice", "Revenue"]].head(10)
)

   Quantity  UnitPrice  Revenue
0         7       4.07    28.49
1        14       4.25    59.50
2         0       3.39     0.00
3        12       3.39    40.68
4        15       3.39    50.85
5         3       4.07    12.21
6         4      14.40    57.60
7         1      21.60    21.60
8         2       0.55     1.10
9         7       4.07    28.49

In [43]:

df["Year"] = df["InvoiceDate"].dt.year

print(df[["InvoiceDate", "Year"]].head(10))

          InvoiceDate  Year
0 2011-09-15 15:26:00  2011
1 2011-06-05 08:10:00  2011
2 2011-07-24 03:45:00  2011
3 2011-09-04 16:55:00  2011
4 2011-02-23 13:40:00  2011
5 2011-02-28 16:38:00  2011
6 2011-07-01 00:08:00  2011
7 2011-09-23 07:36:00  2011
8 2011-03-20 10:39:00  2011
9 2011-09-14 17:41:00  2011

In [44]:

df["Month"] = df["InvoiceDate"].dt.month

print(df[["InvoiceDate", "Month"]].head(10))

          InvoiceDate  Month
0 2011-09-15 15:26:00      9
1 2011-06-05 08:10:00      6
2 2011-07-24 03:45:00      7
3 2011-09-04 16:55:00      9
4 2011-02-23 13:40:00      2
5 2011-02-28 16:38:00      2
6 2011-07-01 00:08:00      7
7 2011-09-23 07:36:00      9
8 2011-03-20 10:39:00      3
9 2011-09-14 17:41:00      9

In [45]:

df["MonthName"] = df["InvoiceDate"].dt.month_name()

print(df[["InvoiceDate", "Month", "MonthName"]].head(10))

          InvoiceDate  Month  MonthName
0 2011-09-15 15:26:00      9  September
1 2011-06-05 08:10:00      6       June
2 2011-07-24 03:45:00      7       July
3 2011-09-04 16:55:00      9  September
4 2011-02-23 13:40:00      2   February
5 2011-02-28 16:38:00      2   February
6 2011-07-01 00:08:00      7       July
7 2011-09-23 07:36:00      9  September
8 2011-03-20 10:39:00      3      March
9 2011-09-14 17:41:00      9  September

In [46]:

import numpy as np

conditions = [
    df["Quantity"] < 0,
    df["Quantity"] == 0,
    df["Quantity"] > 0
]

labels = [
    "Return_or_Cancellation",
    "Zero_Quantity",
    "Positive_Quantity"
]

df["TransactionType"] = np.select(
    conditions,
    labels,
    default="Unknown"
)

print(df["TransactionType"].value_counts())

TransactionType
Positive_Quantity         1488
Return_or_Cancellation     102
Zero_Quantity               10
Name: count, dtype: int64

In [47]:

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nFirst 5 transformed records:")
print(df.head())

Dataset shape: (1600, 13)

Column names:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'Revenue', 'Year', 'Month', 'MonthName', 'TransactionType']

Data types:
InvoiceNo                  object
StockCode                  object
Description                object
Quantity                    int64
InvoiceDate        datetime64[ns]
UnitPrice                 float64
CustomerID                float64
Country                    object
Revenue                   float64
Year                        int32
Month                       int32
MonthName                  object
TransactionType            object
dtype: object

Missing values:
InvoiceNo           0
StockCode           0
Description        23
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID         71
Country            13
Revenue             0
Year                0
Month               0
MonthName           0
TransactionType     0
dtype: int64

First 5 transformed records:
  InvoiceNo StockCode                          Description  Quantity  \
0    570338     71053                  WHITE METAL LANTERN         7
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
2    545052    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         0
3    567005     71053                  WHITE METAL LANTERN        12
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15

          InvoiceDate  UnitPrice  CustomerID      Country  Revenue  Year  \
0 2011-09-15 15:26:00       4.07     16640.0       Sweden    28.49  2011
1 2011-06-05 08:10:00       4.25     17154.0       Sweden    59.50  2011
2 2011-07-24 03:45:00       3.39     16783.0  Netherlands     0.00  2011
3 2011-09-04 16:55:00       3.39     14222.0        Spain    40.68  2011
4 2011-02-23 13:40:00       3.39     16830.0       Sweden    50.85  2011

   Month  MonthName    TransactionType
0      9  September  Positive_Quantity
1      6       June  Positive_Quantity
2      7       July      Zero_Quantity
3      9  September  Positive_Quantity
4      2   February  Positive_Quantity

In [48]:

from pathlib import Path

output_dir = Path("output")
output_dir.mkdir(parents=True, exist_ok=True)

df.to_csv(
    output_dir / "transformed_ecommerce_data.csv",
    index=False
)

print("Transformed dataset saved successfully!")

Transformed dataset saved successfully!

### Phase 5

In [50]:

total_revenue = df["Revenue"].sum()

print("Total Revenue:", round(total_revenue, 2))

Total Revenue: 63231.51

In [51]:

total_quantity = df["Quantity"].sum()

print("Net Quantity:", total_quantity)

Net Quantity: 11478

In [52]:

country_revenue = (
    df.groupby("Country")["Revenue"]
      .sum()
      .sort_values(ascending=False)
)

print(country_revenue)

Country
Belgium           8066.60
Australia         7851.75
EIRE              6916.41
France            6890.19
United Kingdom    6874.97
Spain             5882.50
Germany           5284.96
Sweden            5132.40
Portugal          5088.79
Netherlands       4974.99
Name: Revenue, dtype: float64

In [53]:

top_5_countries = country_revenue.head(5)

print(top_5_countries)

Country
Belgium           8066.60
Australia         7851.75
EIRE              6916.41
France            6890.19
United Kingdom    6874.97
Name: Revenue, dtype: float64

In [54]:

product_revenue = (
    df.groupby("Description")["Revenue"]
      .sum()
      .sort_values(ascending=False)
)

print(product_revenue.head(10))

Description
POSTAGE                                18280.80
REGENCY CAKESTAND 3 TIER               11541.30
SET 7 BABUSHKA NESTING BOXES            7623.99
PINK CHERRY LIGHTS                      6230.25
GLASS STAR FROSTED T-LIGHT HOLDER       3890.45
KNITTED UNION FLAG HOT WATER BOTTLE     3010.48
WHITE METAL LANTERN                     2760.83
WHITE HANGING HEART T-LIGHT HOLDER      2514.81
CREAM CUPID HEARTS COAT HANGER          2108.70
HAND WARMER UNION JACK                  1921.92
Name: Revenue, dtype: float64

In [55]:

product_quantity = (
    df.groupby("Description")["Quantity"]
      .sum()
      .sort_values(ascending=False)
)

print(product_quantity.head(10))

Description
POSTAGE                                1052
PACK OF 60 PINK PAISLEY CAKE CASES     1013
SET 7 BABUSHKA NESTING BOXES            998
WHITE HANGING HEART T-LIGHT HOLDER      973
HAND WARMER UNION JACK                  967
GLASS STAR FROSTED T-LIGHT HOLDER       912
PINK CHERRY LIGHTS                      910
REGENCY CAKESTAND 3 TIER                909
KNITTED UNION FLAG HOT WATER BOTTLE     886
PACK OF 72 RETROSPOT CAKE CASES         856
Name: Quantity, dtype: int64

In [56]:

monthly_revenue = (
    df.groupby(["Year", "Month"])["Revenue"]
      .sum()
      .reset_index()
      .sort_values(["Year", "Month"])
)

print(monthly_revenue)

    Year  Month  Revenue
0   2010     12  4462.03
1   2011      1  5873.46
2   2011      2  4208.40
3   2011      3  4605.15
4   2011      4  5664.60
5   2011      5  4844.46
6   2011      6  5333.89
7   2011      7  4965.49
8   2011      8  4549.29
9   2011      9  5699.21
10  2011     10  6032.83
11  2011     11  5451.54
12  2011     12  1541.16

In [57]:

monthly_summary = (
    df.groupby(["Year", "Month"])
      .agg(
          Total_Revenue=("Revenue", "sum"),
          Total_Quantity=("Quantity", "sum"),
          Transaction_Lines=("InvoiceNo", "size"),
          Unique_Invoices=("InvoiceNo", "nunique")
      )
      .reset_index()
      .sort_values(["Year", "Month"])
)

print(monthly_summary)

    Year  Month  Total_Revenue  Total_Quantity  Transaction_Lines  \
0   2010     12        4462.03             849                134
1   2011      1        5873.46            1058                123
2   2011      2        4208.40             807                120
3   2011      3        4605.15             967                136
4   2011      4        5664.60             910                142
5   2011      5        4844.46             779                118
6   2011      6        5333.89            1038                141
7   2011      7        4965.49             867                121
8   2011      8        4549.29            1002                136
9   2011      9        5699.21             996                127
10  2011     10        6032.83             958                118
11  2011     11        5451.54            1013                146
12  2011     12        1541.16             234                 38

    Unique_Invoices
0               133
1               123
2               120
3               136
4               142
5               118
6               141
7               121
8               136
9               127
10              118
11              145
12               38

In [58]:

customer_summary = (
    df.dropna(subset=["CustomerID"])
      .groupby("CustomerID")
      .agg(
          Total_Spending=("Revenue", "sum"),
          Total_Quantity=("Quantity", "sum"),
          Invoice_Count=("InvoiceNo", "nunique")
      )
      .sort_values("Total_Spending", ascending=False)
)

print(customer_summary.head(10))

            Total_Spending  Total_Quantity  Invoice_Count
CustomerID
12754.0             379.50              24              2
13873.0             376.65              25              2
14828.0             373.50              29              3
15891.0             354.13              26              3
14865.0             324.00              15              1
14646.0             319.47              32              3
14206.0             306.00              24              2
14730.0             305.70              29              2
13594.0             302.40              14              1
16176.0             284.85              19              2

In [59]:

kpi_summary = pd.DataFrame({
    "Metric": [
        "Total Records",
        "Unique Invoices",
        "Unique Products",
        "Unique Countries",
        "Known Customers",
        "Total Revenue",
        "Net Quantity"
    ],
    "Value": [
        len(df),
        df["InvoiceNo"].nunique(),
        df["StockCode"].nunique(),
        df["Country"].nunique(),
        df["CustomerID"].nunique(),
        round(df["Revenue"].sum(), 2),
        df["Quantity"].sum()
    ]
})

print(kpi_summary)

             Metric     Value
0     Total Records   1600.00
1   Unique Invoices   1574.00
2   Unique Products     12.00
3  Unique Countries     10.00
4   Known Customers   1346.00
5     Total Revenue  63231.51
6      Net Quantity  11478.00

In [60]:

from pathlib import Path

output_dir = Path("output")
output_dir.mkdir(parents=True, exist_ok=True)

country_revenue.rename(
    "Revenue"
).to_csv(output_dir / "country_revenue.csv")

product_revenue.rename(
    "Revenue"
).to_csv(output_dir / "product_revenue.csv")

monthly_summary.to_csv(
    output_dir / "monthly_summary.csv",
    index=False
)

kpi_summary.to_csv(
    output_dir / "kpi_summary.csv",
    index=False
)

print("Phase 05 reports saved successfully!")

Phase 05 reports saved successfully!